# Generated by Django 4.2.7 on 2023-11-23 13:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_name_article_title_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_a',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
