# Generated by Django 4.2.7 on 2023-11-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_article_created_a'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='created_a',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
