# Generated by Django 4.2.7 on 2023-11-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_comment_author_alter_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='publications',
            field=models.ManyToManyField(to='myapp.article'),
        ),
    ]
