# Generated by Django 4.2.7 on 2023-11-23 14:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0010_topic_publications'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='prefers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
